# Generated by Django 4.2.7 on 2026-05-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresetcode_delete_passwordresetrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
