# Generated by Django 4.2.7 on 2026-05-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_traininggoal'),
        ('users', '0007_trainerprofile_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='circumference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='goals',
            field=models.ManyToManyField(blank=True, related_name='clients_pursuing', to='catalog.traininggoal'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='home_accessories',
            field=models.ManyToManyField(blank=True, related_name='clients_owning', to='catalog.accessory'),
        ),
    ]
